
localStorage.setItem("answer[1]", "Mangga");
localStorage.setItem("answer[2]", "Nanas");
localStorage.setItem("answer[3]", "Jeruk");
localStorage.setItem("answer[4]", "Manggis");
localStorage.setItem("answer[5]", "Semangka");
localStorage.setItem("answer[6]", "Pisang");
localStorage.setItem("answer[7]", "Melon");
localStorage.setItem("answer[8]", "Alpukat");
localStorage.setItem("answer[9]", "Jambu");
localStorage.setItem("answer[10]", "Kelapa");
localStorage.setItem("answer[11]", "Jagung");
localStorage.setItem("answer[12]", "Brokoli");
localStorage.setItem("answer[13]", "Kentang");
localStorage.setItem("answer[14]", "Tomat");
localStorage.setItem("answer[15]", "Wortel");
localStorage.setItem("answer[16]", "Paprika");
localStorage.setItem("answer[17]", "Labu");
localStorage.setItem("answer[18]", "Cabe");
localStorage.setItem("answer[19]", "Sawi");
localStorage.setItem("answer[20]", "Timun");
var level = 0;
var skor = 0;
var acak = [0,1,2,3,4,5,6,7,8,9];
var answerBuah = shuffle(acak);
var answerSayur = shuffle(acak);
var sayur = [{
    "nama" : "Jagung",
    "namalatin" : "Zea Mays",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Jagung</span> (Zea mays ssp. mays) adalah salah satu tanaman pangan penghasil karbohidrat yang terpenting di dunia, selain gandum dan padi. Bagi penduduk Amerika Tengah dan Selatan, bulir jagung adalah pangan pokok, sebagaimana bagi sebagian penduduk Afrika dan beberapa daerah di Indonesia. Di masa kini, jagung juga sudah menjadi komponen penting pakan ternak. Penggunaan lainnya adalah sebagai sumber minyak pangan dan bahan dasar tepung maizena. Berbagai produk turunan hasil jagung menjadi bahan baku berbagai produk industri. Beberapa di antaranya adalah bioenergi, industri kimia, kosmetika, dan farmasi.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Produk utama jagung adalah bijinya, yang menjadi bahan pangan dan bahan baku pakan. Sebagai bahan pangan, biji jagung direbus lalu dimakan langsung atau digiling kasar menjadi pangan sarapan serealia atau dihaluskan menjadi tepung maizena. SEbagai pakan, jagung kering diberikan langsung atau dipecah atau digiling.Saat ini jagung juga dijadikan sebagai sumber energi alternatif. Lebih dari itu, saripati jagung dapat diubah menjadi polimer sebagai bahan campuran pengganti fungsi utama plastik. Salah satu perusahaan di Jepang telah mencampur polimer jagung dan plastik menjadi bahan baku casing komputer yang siap dipasarkan.</p></div>", 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Biji</span> jagung kaya akan karbohidrat. Sebagian besar berada pada endospermium. Kandungan karbohidrat dapat mencapai 80% dari seluruh bahan kering biji. Karbohidrat dalam bentuk pati umumnya berupa campuran amilosa dan amilopektin. Pada jagung ketan, sebagian besar atau seluruh patinya merupakan amilopektin. Perbedaan ini tidak banyak berpengaruh pada kandungan gizi, tetapi lebih berarti dalam pengolahan sebagai bahan pangan. Jagung manis diketahui mengandung amilopektin lebih rendah tetapi mengalami peningkatan fitoglikogen dan sukrosa.[12].</p></div>" 
},
{
    "nama" : "Brokoli",
    "namalatin" : "Brassica oleracea",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Brokoli</span> adalah anggota dari keluarga kubis, dan terkait erat dengan kembang kol. Budidaya berasal di Italia. Broccolo, nama Italia tersebut, berarti ” kubis tumbuh. ” Nama Brokoli adalah berasal dari kata Latin brachium, yang berarti cabang atau lengan, merupakan cerminan bentuk seperti pohon yang yang memiliki kepala kompak kuntum melekat dengan batang kecil untuk batang yang lebih besar. Karena komponen yang berbeda, sayuran ini menyediakan kompleks selera dan tekstur, mulai dari lembut dan bunga-bunga ( floret ) ke berserat dan renyah ( batang dan tangkai ). Warnanya bervariasi dari sage mendalam untuk hijau gelap ke ungu – hijau, tergantung pada varietas. Salah satu jenis yang paling populer dari brokoli dijual di Amerika Utara dikenal sebagai Italia hijau, atau Calabrese, dinamai provinsi Italia Calabria di mana pertama kali tumbuh.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Manfaat</span> brokoli terbukti sangat banyak diantaranya untuk kesehatan mata dan syaraf dan ikut mengurangi tekanan darah. Disamping itu kandungan kalsium dan vitamin K yang tinggi membuat sayur brokoli juga sangat baik untuk kesehatan tulang. Hal menarik lain dari sayuran hijau ini adalah manfaatnya untuk kesehatan kulit juga cukup besar.</p></div>", 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Sebagai</span> makanan, brokoli biasanya direbus atau dikukus, atau dapat pula dimakan mentah. Cara terbaik dalam mengolah brokoli adalah dengan cara dikukus. Hal ini bertujuan agar segala vitamin dan nutrisi penting di dalamnya tidak hilang selama proses pemasakan. Merebus brokoli akan menghilangkan sekitar 50 % asam folat yang terkandung di dalamnya. Oleh karena itu, jika ingin mengolah brokoli dengan cara direbus, sebaiknya brokoli tidak direbus terlalu lama, kira-kira tidak lebih dari 5 menit.[1] Brokoli mengandung vitamin C dan serat makanan dalam jumlah banyak. Brokoli juga mengandung senyawa glukorafanin, yang merupakan bentuk alami senyawa antikanker sulforafana (sulforaphane). Selain itu, brokoli mengandung senyawaan isotiosianat yang, sebagaimana sulforafana, ditengarai memiliki aktivitas antikanker[2].</p></div>" 
},
{
    "nama" : "Kentang",
    "namalatin" : "Solanum tuberosum",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Solanum</span> tuberosum atau yang lebih dikenal sebagai kentang merupakan tanaman setahun, bentuk sesungguhnya menyamak dan bersifat menjalar. Batangnya berbentuk segi empat, panjang bisa mencapai 50 – 120 cm dan tidak berkayu. Batang dan daun berwarna hijau kemerah-merahan atau keungu-unguan. Akar tanaman menjalar dan berukuran sangat kecil bahkan sangat halus. Selain mempunyai organ-organ di atas, kentang juga mempunyai organ umbi. Umbi tersebut berasal dari cabang samping yang masuk ke dalam tanah. Cabang ini merupakan tempat untuk menyimpan karbohidrat sehingga membengkak dan bisa dimakan. Umbi bisa mengeluarkan tunas dan nantinya akan membentuk cabang-cabang baru. Kentang termasuk tanaman setahun yang ditanam untuk dipanen umbinya. Umbi kentang merupakan ujung stolon yang membesar  dan merupakan organ penyimpanan yang mengandung karbohidrat yang tinggi (Setiadi dan Nurulhuda, 1998).</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Manfaat</span> kentang sudah lama dijadikan menu diet bagi orang-orang yang memiliki keluhan gejala penyakit diabetes. Kentang termasuk keluarga umbi-umbian yang berasal dari Amerika, dan sudah dibudidayakan pada negara-negara lain termasuk Indonesia. Pada negara asalnya sendiri, kentang sudah dijadikan makanan pokok bagi penduduknya. Tidak mengherankan karena kentang merupakan salah satu penghasil karbohidrat sebagai sumber energi. Pada kandungan sebuah kentang, tersimpan manfaat yang baik bagi tubuh.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Pada </span>kentang terkandung zat-zat seperti karbohidrat, fosfor, zat besi, protein, lemak nabati dan kalsium serta mineral-mineral penting lainnya. Hal ini yang menjadikan kentang baik dikonsumsi dalam menu makan sehari-hari. Berikut adalah berbagai kandungan gizi Kentang yang terdapat dalam satu porsi 173 Gr Kentang</p></div>"  
},
{
    "nama" : "Tomat",
    "namalatin" : "Solanum lycopersicum",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Tomat</span> (Solanum lycopersicum syn. Lycopersicum esculentum) adalah tumbuhan dari keluarga Solanaceae, tumbuhan asli Amerika Tengah dan Selatan, dari Meksiko sampai Peru. Tomat merupakan tumbuhan siklus hidup singkat, dapat tumbuh setinggi 1 sampai 3 meter. Tomat merupakan keluarga dekat dari kentang.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Orang</span> mengenal tomat buah, tomat sayur, serta tomat lalapan. Berdasarkan hal ini, fungsi tomat merupakan klasifikasi dari buah maupun sayuran, walaupun struktur tomat adalah struktur buah. Perkembangan pengetahuan, sekarang tomat tidak hanya sebagai pelengkap untuk makanan melainkan juga sudah dikenal luas untuk kecantikan. Manfaat tomat untuk kecantikan antara lain adalah untuk mengecilkan pori-pori dan mencerahkan kulit karena tomat kaya dengan kandungan vitamin C.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Di</span> dunia kuliner, tomat sering dijadikan bahan pelengkap masakan karena akan memberikan efek segar pada masakan. Dan tomat juga sering dijadikan penghias makanan agar tampilannya lebih menarik. Sedangkan Di dunia kesehatan, tomat sering dijadikan juss karena sangat menyehatkan apalagi di konsumsi secara rutin. Namun tahukah anda bahwa ternyata tomat memiliki kandungan dan khasiat yang luar biasa yang tidak di miliki oleh buah – buahan lainnya. </p></div>"  
},
{
    "nama" : "Wortel",
    "namalatin" : "Daucus carota",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Wortel</span> adalah tumbuhan biennial (siklus hidup 12 - 24 bulan) yang menyimpan karbohidrat dalam jumlah besar untuk tumbuhan tersebut berbunga pada tahun kedua. Batang bunga tumbuh setinggi sekitar 1 m, dengan bunga berwarna putih, dan rasa yang manis langu. Bagian yang dapat dimakan dari wortel adalah bagian umbi atau akarnya.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Wortel</span> dapat dimakan dengan berbagai cara. Pada wortel mentah hanya 3% β-ririencha yang dilepaskan selama proses pencernaan, proses ini dapat ditingkatkan hingga 39% melalui pulping, memasaknya dan menambahkan minyak sawit. Bisa juga dengan cara di buat jus wortel dan kandungan vitaminnya hampir sama dengan wortel yang dimakan begitu saja.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Wortel</span> mengandung vitamin A yang baik untuk kesehatan mata. Mengkonsumsi wortel baik untuk penglihatan pada mata, terutama bisa meningkatkan pandangan jarak jauh. Selain vitamin A, wortel juga mengandung vitamin B1, B2, B3, B6, B9, dan C, kalsium, zat besi, magnesium, fosfor, kalium, dan sodium.</p></div>"  
},
{
    "nama" : "Paprika",
    "namalatin" : "Capsicum annuum",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Paprika</span> (Capsicum annuum L.) adalah tumbuhan penghasil buah yang berasa manis dan sedikit pedas dari suku terong-terongan atau Solanaceae). Buahnya yang berwarna hijau, kuning, merah, atau ungu sering digunakan sebagai campuran salad. Dalam pengertian internasional, paprika dipakai untuk menyatakan hampir semua varietas C. annuum, termasuk yang pedas. Nama-nama tertentu, seperti pepperoni, diberikan untuk paprika dengan ciri penampilan, penggunaan, atau rasa yang khas. Tanaman ini berasal dari Amerika Selatan, sekarang tersebar luas dan dibudidayakan di hampir semua daerah tropika dan subtropika.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Paprika</span> dapat dimakan pada setiap tahap pembangunan. Namun, penelitian terbaru menunjukkan bahwa vitamin C dan karotenoid dari paprika cenderung meningkat sementara lada mencapai kematangan optimal. Paprika juga biasanya lebih beraroma ketika optimal matang.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Anda</span> tidak ingin mereka untuk menjadi terlalu matang ke titik terlalu lembut, keriput, atau karatan. Bahkan, jika paprika yang optimal matang pada saat pembelian, mereka dapat kehilangan hingga 15 % dari kandungan vitamin C mereka selama penyimpanan 10 hari dalam lemari es dan sampai 25 % dari mereka vitamin C lebih dari 20 – hari waktu penyimpanan kulkas. Namun, jika tidak optimal matang pada saat pembelian, vitamin C dan karotenoid dalam paprika akan benar-benar meningkatkan dengan penyimpanan lemari es selama 10 hari ke depan. Jadi seperti yang Anda lihat, ada keseimbangan dalam hal kematangan yang optimal ! Kami mendorong Anda untuk tidak khawatir tentang makan paprika yang belum optimal matang, karena mereka masih dapat memberikan manfaat kesehatan yang luar biasa. Tapi untuk yang optimal vitamin C dan karotenoid manfaat, Anda mungkin ingin bereksperimen sedikit dan lihat apakah Anda dapat mengembangkan keterampilan untuk mengevaluasi kematangan dalam sayuran ini.</p></div>"  
},
{
    "nama" : "Labu",
    "namalatin" : "Cucurbitaceae sp.",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Labu merupakan buah yang dihasilkan oleh sejumlah anggota suku labu-labuan (Cucurbitaceae), terutama yang berukuran cukup besar dan berbentuk bulat atau memanjang. Tidak ada kriteria yang jelas mengenai pemanfaatannya, sehingga labu dapat dimakan segar atau diolah terlebih dahulu; namun labu biasanya tidak dimakan sebagai lalapan.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Manfaat</span> labu untuk kesehatan yaitu untuk menstabilkan gula darah dengan menjaga pola makan karena kandungan labu merupakan jenis kalori yang rendah gula, meskipun demikian tetap memberikan manfaat untuk tubuh anda dengan memberikan sumber energi. Kandungan magnesium yang terdapat pada labu membuat anda lebih tenang karena mampu membuat rileks saraf, selain itu biji labu mengandung zat besi yang sangat dibutuhkan untuk menjaga kesehatan terutama anemia yang sering terjadi pada wanita. Bagi anda yang ingin melancarkan pencernaan konsumsi labu untuk menjaga pencernaan terutama usus manusia. Bagi anda yang ingin menjaga kesehatan sediakan labu dalam menu makanan anda sehari-hari. Anda dapat membuatnya secara bervariasi dari mulai sayur labu atau cemilan yang berbahan dasar labu.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Labu</span> adalah salah satu sayuran yang  sangat rendah kalori. 100 buah g hanya menyediakan 26 kalori dan tidak mengandung lemak jenuh atau kolesterol, namun kaya serat makanan, anti-oksidan, mineral, vitamin. Labu adalah salah satu sayuran yang direkomendasikan oleh para ahli medis untuk mengurangi kolestrol dan penurunan berat badan.Labu merupakan sayuran yang memiliki banyak vitamin anti-oksidan seperti vitamin A, vitamin C dan vitamin E. Labu dalam 100 gram mengandung vitamin A tertinggi dari keluarga sayuran Cucurbitaceae yang mengandung sekitar 246% dari RDA. Vitamin A adalah anti-oksidan alami yang kuat dan diperlukan oleh tubuh untuk menjaga integritas kulit dan membran lendir. Ini juga merupakan vitamin penting untuk penglihatan visual yang baik. Studi penelitian menunjukkan bahwa makanan alami kaya vitamin A membantu tubuh melindungi terhadap paru-paru dan kanker rongga mulut. Labu adalah jenis sayuran yang megandung anti-oksidan alami yang memiliki UV (ultra violet) sinar penyaringan tindakan dalam lutea makula di retina mata. Dengan demikian, hal ini membantu melindungi dari penyakit makula terkait usia (ARMD) pada orang tua. Kandungan dari labu adalah sumber yang baik dari kelompok B-kompleks vitamin seperti folat, niacin, vitamin B-6 (pyridoxine), thiamin, dan asam pantotenat.Selain itu mengandung mineral seperti tembaga, kalsium, kalium dan fosfor. Tidak saja daging labu akan tetapi kandungan dari biji labu merupakan nutrisi yang sangat baik mengandung serat dan asam lemak tak jenuh yang baik untuk kesehatan jantung. Selain itu, biji terkonsentrasi sumber protein, mineral dan kesehatan-manfaat vitamin. Misalnya 100 g biji labu menyediakan 559 kalori, 30 g protein, 110% RDA besi, 4987 mg niacin (31% RDA), selenium (17% RDA), seng (71%).Selanjutnya, biji labu merupakan nutrisi yang baik untuk menjaga kesehatan terutama kandungan asam amino triptofan untuk kesehatan otak.</p></div>"  
},
{
    "nama" : "Cabe",
    "namalatin" : "Capsicum sp.",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Cabai</span> adalah kerabat lada dan termasuk dalam suku sirih-sirihan atau Piperaceae. Dikenal pula sebagai cabai solak (Madura) dan cabia (Sulawesi). Tumbuhan asli Indonesia ini populer sebagai tanaman obat pekarangan dan tumbuh pula di hutan-hutan sekunder dataran rendah (hingga 600m di atas permukaan laut). Tumbuhan ini produknya telah dikenal oleh orang Romawi sejak lama dan sering dikacaukan dengan lada. Di Indonesia sendiri buah keringnya digunakan sebagai rempah pemedas. Sebelum kedatangan cabai (Capsicum spp.), tumbuhan inilah yang disebut "cabe". Cabai sendiri oleh orang Jawa dinamakan "lombok". Cabai jamu dapat tumbuh di lahan ketinggian 0-600 meter di atas permukaan laut (dpl), dengan curah hujan rata-rata 1.259-2.500 mm/tahun. Tanah lempung berpasir, dengan struktur tanah gembur dan berdrainase baik, merupakan lahan yang cocok untuk budidaya cabe jamu. Tanaman itu memiliki keunggulan dapat tumbuh di lahan kering berbatu. Keberadaan tanggul batu di pematang tegalan dapat dijadikan media merambatnya cabe jamu secara alami. Bentuk tanamannya seperti sirih, merambat, memanjat, membelit, dan melata. Daunnya berbentuk bulat telur sampai lonjong, pangkal daun berbentuk jantung atau membulat, ujung daun runcing dengan bintik-bintik kelenjar. buahnya majemuk bulir, bentuknya bulat panjang atau silindris, dan ujungnya mengecil. Buah yang belum tua berwarna kelabu, kemudian menjadi hijau, selanjutnya kuning, merah, serta lunak. Rasanya pedas dan tajam aromatis.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Cabai</span> merah Besar (Capsicum annuum L.) merupakan salah satu jenis sayuran yang memilki nilai ekonomi yang tinggi. Cabai mengandung berbagai macam senyawa yang berguna bagi kesehatan manusia. [1]. Sun et al. (2007) melaporkan cabai mengandung antioksidan yang berfungsi untuk menjaga tubuh dari serangan radikal bebas. Kandungan terbesar antioksidan ini adalah pada cabai hijau. Cabai juga mengandung Lasparaginase dan Capsaicin yang berperan sebagai zat antikanker (Kilham 2006; Bano & Sivaramakrishnan 1980). Cabai (Capsicum annum L) merupakan salah satu komoditas sayuran yang banyak dibudidayakan oleh petani di Indonesia karena memiliki harga jual yang tinggi [2] dan memiliki beberapa manfaat kesehatan yang salah satunya adalah zat capsaicin yang berfungsi dalam mengendalikan penyakit kanker. Selain itu kandungan vitamin C yang cukup tinggi pada cabai dapat memenuhi kebutuhan harian setiap orang, namun harus dikonsumsi secukupnya untuk menghindari nyeri lambung.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'> Buah</span> cabai jamu memiliki khasiat sebagai obat sakit perut, masuk angin, beri-beri, rematik, tekanan darah rendah, kolera, influenza, sakit kepala, lemah syahwat, bronkitis, dan sesak napas. Karena itu, cabe jamu banyak dibutuhkan sebagai bahan pembuatan jamu tradisional dan obat pil/kapsul modern serta bahan campuran minuman. Rasa pedas itu berasal dari senyawa piperin, dengan kandungan sekitar 4,6 persen.</p></div>"  
},
{
    "nama" : "Sawi",
    "namalatin" : "Brassica rapa",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Sawi </span>hijau (Brassica rapa convar. parachinensis; suku sawi-sawian atau Brassicaceae) merupakan jenis sayuran yang cukup populer. Dikenal pula sebagai caisim, caisin, atau sawi bakso, sayuran ini mudah dibudidayakan dan dapat dimakan segar (biasanya dilayukan dengan air panas) atau diolah menjadi asinan (kurang umum). Jenis sayuran ini mudah tumbuh di dataran rendah maupun dataran tinggi. Bila ditanam pada suhu sejuk tumbuhan ini akan cepat berbunga. Karena biasanya dipanen seluruh bagian tubuhnya (kecuali akarnya), sifat ini kurang disukai. Pemuliaan sawi ditujukan salah satunya untuk mengurangi kepekaan akan suhu ini.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Karena</span> mudah tumbuh dan responsif terhadap perubahan lingkungan, sawi hijau sering dimanfaatkan sebagai tumbuhan percobaan untuk pemupukan, kesuburan tanaman, gangguan karena kurangan hara, serta bioremediasi.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Sawi</span> banyak mengandung vitamin dan mineral. Kadar vitamin K, A, C, E, dan folat pada sawi tergolong dalam kategori excellent. Mineral pada sawi yang tergolong dalam kategori excellent adalah mangan dan kalsium. Sawi juga excellent dalam hal asam amino triptofan dan serat pangan (dietaryfiber).</p></div>"  
},
{
    "nama" : "Timun",
    "namalatin" : "Cucumis sativus",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Mentimun,</span> timun, atau ketimun (Cucumis sativus L.; suku labu-labuan atau Cucurbitaceae) merupakan tumbuhan yang menghasilkan buah yang dapat dimakan. Buahnya biasanya dipanen ketika belum masak benar untuk dijadikan sayuran atau penyegar, tergantung jenisnya. Mentimun dapat ditemukan di berbagai hidangan dari seluruh dunia dan memiliki kandungan air yang cukup banyak di dalamnya sehingga berfungsi menyejukkan. Potongan buah mentimun juga digunakan untuk membantu melembabkan wajah serta banyak dipercaya dapat menurunkan tekanan darah tinggi.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Manfaat</span> Mentimun Mentimun memiliki sifat diuretik, efek pendingin, dan pembersih yang bermanfaat bagi kulit. Kandungan air yang tinggi; vitamin A, B, dan C; serta mineral, seperti magnesium, kalium, mangan, dan silika; membuat mentimun menjadi bagian penting dalam perawatan kulit. Masker wajah yang mengandung sari mentimun digunakan untuk mengencangkan kulit. Asam askorbat dan asam caffeic yang hadir dalam mentimun dapat menurunkan tingkat retensi air, yang pada gilirannya mengurangi pembengkakan di sekitar mata.</p></div>",
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Dalam setiap 100 gram timun mengandung: Gula – 1,67 gm, Karbohidrat – 3,63 gm, Serat Diet – 0,5 gm, Riboflavin (Vitamin B2) – 0,033 mg, Niacin (Vitamin B3) – 0,098 mg, Asam Pantothenic (Vitamin B5) – 0,259 mg, Thiamin (Vitamin B1) – 0,027 mg, Vitamin B6 – 0,040 mg, Lemak – 0,11 gm, Protein – 0,65 gm, Vitamin C – 2,8 mg, Asam Folat (Vitamin B9) – 7 μg, Zat besi – 0,28 mg, Calcium – 16 mg, Magnesium – 13 mg, Fosfor – 24 mg, Zinc- 0,20 mg, dan Potassium – 147 mg.</p></div>"  
}];
var buah = [{
    "nama" : "Mangga",
    "namalatin" : "Mangifera Indica",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Mangga</span> atau mempelam adalah nama sejenis buah, demikian pula nama pohonnya. Mangga termasuk ke dalam marga Mangifera, yang terdiri dari 35-40 anggota, dan suku Anacardiaceae. Nama ilmiahnya adalah Mangifera indica.</p><p><span style="margin-left:30px">Pohon</span> manggatermasuk tumbuhan tingkat tinggi yang struktur batangnya (habitus) termasuk kelompok arboreus, yaitu tumbuhan berkayu yang mempunyai tinggi batang lebih dari 5 m. Mangga bisa mencapai tinggi 10-40 m.</p><p><span style="margin-left:30px">Nama</span> buah ini berasal dari Malayalam maanga. Kata ini dipadankan dalam bahasa Indonesia menjadi mangga; dan pada pihak lain, kata ini dibawa ke Eropa oleh orang-orang Portugis dan diserap menjadi manga (bahasa Portugis), mango (bahasa Inggris) dan lain-lain. Nama ilmiahnya sendiri kira-kira mengandung arti: “(pohon) yang berbuah mangga, berasal dari India”. Berasal dari sekitar perbatasan India dengan Burma, mangga telah menyebar ke Asia Tenggara sekurangnya semenjak 1500 tahun yang silam. Buah ini dikenal pula dalam berbagai bahasa daerah, seperti pelem atau poh</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Mangga</span> terutama ditanam untuk buahnya. Buah yang matang umum dimakan dalam keadaan segar, sebagai buah meja atau campuran es, dalam bentuk irisan atau diblender. Buah yang muda kerap kali dirujak, atau dijajakan di tepi jalan setelah dikupas, dibelah-belah dan dilengkapi bumbu garam dengan cabai. Buah mangga juga diolah sebagai manisan, irisan buah kering, dikalengkan dan lain-lain. Di pelbagai daerah di Indonesia, mangga (tua atau muda) yang masam kerap dijadikan campuran sambal atau masakan ikan dan daging.</p><p><span style='margin-left:30px'>Biji</span> mangga dapat dijadikan pakan ternak atau unggas; di India bahkan dijadikan bahan pangan di masa paceklik. Daun mudanya dilalap atau dijadikan sayuran. Kayu mangga cukup kuat, keras dan mudah dikerjakan; namun kurang awet untuk penggunaan di luar. Kayu ini juga dapat dijadikan arang yang baik.</p><p><span style='margin-left:30px'>Daun</span> mangga mengandung senyawa organik tarakserol-3beta dan ekstrak etil asetat yang bersinergis dengan insulin mengaktivasi GLUT4, dan menstimulasi sintesis glikogen, sehingga dapat menurunkan gejala hiperglisemia.</p><p><span style='margin-left:30px'>Mangga</span> terutama dihasilkan oleh negara-negara India, Tiongkok, Meksiko, Thailand, Pakistan, Indonesia, Brasil, Filipina, dan Bangladesh. Total produksi dunia pada tahun ‘80an sekitar 15 juta ton, namun hanya sekitar 90.000 ton (1985) yang diperdagangkan di tingkat dunia. Artinya, sebagian besar mangga dikonsumsi secara lokal.</p><p><span style='margin-left:30px'>Sementara</span> itu pasar utama mangga adalah Asia Tenggara, Eropa, Amerika Serikat dan Jepang. Singapura, Hong Kong dan Jepang merupakan pengimpor yang terbesar di Asia. Gambaran produksi mangga tahun 2007 dapat dilihat pada tabel di bawah.</p></div>", 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Karena</span> ketidaktahuan dan kurangnya informasi, banyak di antara kita yang menganggap biji mangga hanya sekedar limbah rumah tangga. Padahal penelitian lanjutan para ahli membuktikan manfaat biji mangga cukup signifikan jika diolah dengan benar. Khasiat ini tentu tak lepas dari kandungan senyawa yang ada di dalam biji mangga itu sendiri. Zat yang terbukti terkandung di dalamnya antara lain karbohidrat sejumlah 19.52% dari berat total biji, lemak sebanyak 3,80% dari total berat biji mangga dan protein sebanyak 3.78% dari berat total biji mangga. Penelitian ini membuktikan bahwa biji mangga, selain berfungsi sebagai bibit mangga, juga bisa dijadikan sumber karbohidrat yang baik. Tahukah Anda, saat musim paceklik menyerang India, masyarakatnya akan memanfaatkan biji mangga ini sebagai pengganti beras dan gandum.</p></div>" 
},
{
    "nama" : "Nanas",
    "namalatin" : "Ananas comosus",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Berdasarkan</span> habitat tanaman, terutama bentuk daun dan buah dikenal 4 jenis golongan nanas, yaitu : Cayenne (daun halus, tidak berduri, buah besar), Queen (daun pendek berduri tajam, buah lonjong mirip kerucut), Spanyol/Spanish (daun panjang kecil, berduri halus sampai kasar, buah bulat dengan mata datar) dan Abacaxi (daun panjang berduri kasar, buah silindris atau seperti piramida). Varietas kultivar nanas yang banyak ditanam di Indonesia adalah golongan Cayene dan Queen. Golongan Spanish dikembangkan di kepulauan India Barat, Puerte Rico, Mexico dan Malaysia. Golongan Abacaxi banyak ditanam di Brazilia. Dewasa ini ragam varietas/kultivar nanas yang dikategorikan unggul adalah nanas Bogor, Subang dan Palembang</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Nanas</span> memiliki manfaat yang beragam, manfaat nanas tersebut adalah sebagai berikut :<br/>Pencernaan protein akan bertambah lancar. Manfaat tersebut dapat kita peroleh karena buah nanas mengandung banyak enzim bromelain. Enzim inilah yang bermanfaat sebagai pelega tenggorokan dan memperlancar proses pencernaan.Jadi enzim inilah yang berfungsi untuk mencerna protein sehingga dapat diserap oleh tubuh.<br/>Proses penyembuhan luka semakin cepat. Tak hanya itu, ternyata enzim bromelain juga berfungsi untuk mempercepat proses penyembuhan luka, serta mengurangi peradangan atau pembengkakan dalam tubuh.Oleh karena itu, bagi pasien yang baru saja selesai melakukan operasi sangat baik mengkonsumsi buah nanas.<br/>Nanas berfungsi sebagai pembersih. Nanas sebagai pembersih juga diperoleh karena adanya enzim bromelain yang membantu menjaga keseimbangan kadar asam dalam darah. Nanas juga memiliki manfaat untuk mengurangi kadar air dalam tubuh bila berlebihan, oleh karena itu nanas juga dapat mencegah penyakit edema. Ada zat lain yang terkandung didalam nanas selain enzim bromelain, yaitu asam aspartic. Asam ini berfungsi untuk mengeluarkan asam amonia yang merupakan racun dalam tubuh.</p></div>", 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Buah</span> ini banyak mengandung vitamin A dan C sebagai antioksidan. Juga mengandung kalsium, fosfor, magnesium, besi, natrium, kalium, dekstrosa, sukrosa, dan enzim bromelain. Bromelain berkhasiat sebagai antiradang, membantu melunakkan makanan di lambung, serta menghambat pertumbuhan sel kanker. Kandungan seratnya dapat mempermudah buang air besar pada penderita sembelit. </p></div>" 
},
{
    "nama" : "Jeruk",
    "namalatin" : "Citrus Reticulata",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Jeruk</span> atau limau adalah semua tumbuhan berbunga anggota marga Citrus dari suku Rutaceae (suku jeruk-jerukan). Anggotanya berbentuk pohon dengan buah yang berdaging dengan rasa masam yang segar, meskipun banyak di antara anggotanya yang memiliki rasa manis. Rasa masam berasal dari kandungan asam sitrat yang memang menjadi terkandung pada semua anggotanya.<br/>Sebutan "jeruk" kadang-kadang juga disematkan pada beberapa anggota marga lain yang masih berkerabat dalam suku yang sama, seperti kingkit. Dalam bahasa sehari-hari, penyebutan "jeruk" atau "limau" (di Sumatra dan Malaysia) seringkali berarti "jeruk keprok" atau "jeruk manis". Di Jawa, "limau" (atau "limo") berarti "jeruk nipis".</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Manfaat</span> pertama yaitu jeruk sangat baik untuk mencegah penyakit kanker seperti kanker kulit, payudara, paru-paru, mulut dan usus besar. Ini dikarenakan buah jeruk mengandung D-limonene yang merupakan senyawa yang sangat baik untuk mencegah berbagai kanker tersebut.<br/>Bagi anda yang bermasalah dengan kadar kolersterol yang tinggi, maka mengkonsumsi jeruk merupakan salah satu solusi yang dapat anda ambil. Ini dikarenakan, buah jeruk mengandung Hesperidin dan Pectin. kedua zat tersebut sangat baik untuk menurunkan kadar kolesterol dalam tubuh anda.<br/>Anda memiliki tekanan darah yang tinggi...??? Maka mengkonsumsi buah jeruk juga sangat baik untuk menurunkan tekanan darah tinggi anda. Ini dikarenakan buah jeruk mengandung Hesperidin dan magnesium yang berfungsi menurunkan tekanan darah tinggi anda..<br/>Anda mengalami radang sendi atau kekakuan pada otot dan sendi anda....???. Maka mengkonsumsi buah jeruk merupakan alternatif yang dapat anda ambil. Ini dikarenakan buah jeruk terbukti dapat mengurangi radang pada sendi atau kekakuan pada otot dan sendi anda..<br/>Buah jeruk ternyata sangat baik untuk perkembangan otak anda. Ini dikarenakan buah jeruk mengandung asam folat yang merupakan zat yang sangat baik untuk membantu perkembangan otak anda...<br/>Manfaat berikutnya yaitu, buah jeruk juga sangat baik untuk memperkuat sistem kekebalan tubuh anda. Ini dikarenakan buah jeruk merupakan sumber vitamin C. Fungsi vitamin C yaitu merangsang produksi sel darah putih dalam tubuh kita. Sehingga sangat baik dan dapat meningkatkan sistem kekebalan pada tubuh kita.Buah jeruk juga mengandung zat antioksidan. Fungsi antioksidan yaitu dapat membantu melindungi kulit dari kerusakan yang diakibatkan oleh radikal bebas Sehingga anda akan tampak lebih awet muda.dengan rajin mengkonsumsi buah jeruk tersebut.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Kandungan</span> jeruk nipis setiap 100 g nya, terdapat 51 kal kalori, 0,9 g protein, 0,2 g lemak, 11,4 gkarbohidrat, 0,5 g mineral, 33 mg kalsium, 23 mg fosfor, 0,4 mg besi, dan 49 mgasam askorbat. Jeruk nipis juga mengandung asam sitrat, asam amino (triptofan, lisin), minyak atsiri (sitral, limonen, felandren, lemon kamfer, kadinen, gerani-lasetat, linali-lasetat, aktilaldehid, nildehid) damar, glikosida, asam sitrun, vitamin B1, dan C. </p></div>"  
},
{
    "nama" : "Manggis",
    "namalatin" : "Garcinia mangostana",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Manggis</span> (Garcinia mangostana L.) adalah sejenis pohon hijau abadi dari daerah tropika yang diyakini berasal dari Kepulauan Nusantara. Tumbuh hingga mencapai 7 sampai 25 meter. Buahnya juga disebut manggis, berwarna merah keunguan ketika matang, meskipun ada pula varian yang kulitnya berwarna merah. Buah manggis dalam perdagangan dikenal sebagai "ratu buah", sebagai pasangan durian, si "raja buah". Buah ini mengandung mempunyai aktivitas antiinflamasi dan antioksidan. Sehingga di luar negeri buah manggis dikenal sebagai buah yang memiliki kadar antioksidan tertinggi di dunia.Manggis berkerabat dengan kokam, asam kandis dan asam gelugur, rempah bumbu dapur dari tradisi boga India dan Sumatera.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Daging</span> buah, biji  hingga kulit buah manggis ini dapat diekstrak menjadi makanan serta mninuman kesehatan kelas premium. Kulit pada buah manggis ini sangat bermanfaat untuk tubuh manusia oleh sebab itu banyak yang memanfaatkan kulit manggis untuk kesehatan tubuh manusia serta kecantikan. kandungan antioksidan yang tinggi membuat buah manggis dapat menyembuhkan beragam penyakit, dimulai dari yang mudah sampai kanker. </p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Buah manggis  kaya akan  vit. b1, b2 serta c, dan kalsium, potassium, sodiumdan zat besi.  Buah manggis juga memiliki kandungan xanthone, mangostin, garsinon, flavonoid, epicatechin, spingomyolinase serta gartanin. didalam kulit buahnya, kandungan xanthone yang paling tinggi, yakni 40 %, dengan kandungan xanthone yang tinggi( , 97 mg/ml ), didalam kulit buah manggis yang mana bisa membunuh penyakit serta melakukan perbaikan sel yang sudah rusak dan membuat perlindungan beberapa sel didalam tubuh. xanthone yaitu substansi kimia alami, yang tergolong senyawa polyhenolic yang bisa dipakai sebagai zat untuk menangani beragam penyakit. xanthone mempunyai manfaat sebagai penyembuhan untuk penyakit jantung, aterosklorosis ( plak di pembuluh darah ), hipertensi serta trombosis.</p></div>"  
},
{
    "nama" : "Semangka",
    "namalatin" : "Citrullus lanatus",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Semangka</span> atau tembikai (Citrullus lanatus, suku ketimun-ketimunan atau Cucurbitaceae) adalah tanaman merambat yang berasal dari daerah setengah gurun di Afrika bagian selatan. Tanaman ini masih sekerabat dengan labu-labuan (Cucurbitaceae), melon (Cucumis melo) dan ketimun (Cucumis sativus). Semangka biasa dipanen buahnya untuk dimakan segar atau dibuat jus. Biji semangka yang dikeringkan dan disangrai juga dapat dimakan isinya (kotiledon) sebagai kuaci.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Dapat</span> menemani program diet anda karena buah semangka ini merupakan salah satu buah yang tidak mengandung lemak dan juga mempunyai kombinasi kadar gula terbatas dan kandungan air yang cukup banyak. Sangat bermanfaat bagi penderita hipertensi karena memiliki kandungan air dan kalium cukup tinggi yang dapat menetralisasikan tekanan darah di dalam tubuh kita.Dapat mempergiat kerja jantung. Dapat membantu tubuh kita tetap sehat karena mengandung antioksidan (betakaroten dan vitamin C). Dapat merangsang keluarnya air seni lebih deras. Dapat menurunkan demam. Dapat mencegah sariawan dengan cepat.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Buah</span> semangka (citrullus lanatus) selain banyak mengandung air, isinya yang berwarna merah ini mempunyai banyak kandungan gizi serta banyak mengandung zat yang bisa mencegah berbagai penyakit. Buah semangka juga kaya vitamin A dan beta karoten, vitamin C, Lutein dan Zeaxanthin yang berguna sebagai alat perlindungan mata  sehingga memaksimalkan kesehatan mata. </p></div>"  
},
{
    "nama" : "Pisang",
    "namalatin" : "Musa acuminata",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Pisang</span> adalah nama umum yang diberikan pada tumbuhan terna raksasa berdaun besar memanjang dari suku Musaceae. Beberapa jenisnya (Musa acuminata, M. balbisiana, dan M. ×paradisiaca) menghasilkan buah konsumsi yang dinamakan sama. Buah ini tersusun dalam tandan dengan kelompok-kelompok tersusun menjari, yang disebut sisir. Hampir semua buah pisang memiliki kulit berwarna kuning ketika matang, meskipun ada beberapa yang berwarna jingga, merah, hijau, ungu, atau bahkan hampir hitam. Buah pisang sebagai bahan pangan merupakan sumber energi (karbohidrat) dan mineral, terutama kalium.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Berdasarkan</span> cara konsumsi buahnya, pisang dikelompokkan dalam dua golongan, yaitu pisang meja (dessert banana) dan pisang olah (plantain, cooking banana). Pisang meja dikonsumsi dalam bentuk segar setelah buah matang, seperti pisang ambon, susu, raja, seribu, dan sunripe. Pisang olahan dikonsumsi setelah digoreng, direbus, dibakar, atau dikolak, seperti pisang kepok, siam, kapas, tanduk, dan uli.Buah pisang diolah menjadi berbagai produk, seperti sale, kue, ataupun arak (di Amerika Latin).Selain memberikan kontribusi gizi lebih tinggi daripada apel, pisang juga dapat menyediakan cadangan energi dengan cepat bila dibutuhkan. Termasuk ketika otak mengalami keletihan. Beragam jenis makanan ringan dari pisang yang relatif populer antara lain Kripik Pisang asal Lampung, Sale pisang(Bandung), Pisang Molen (Bogor), dan epe (Makassar).</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Pisang</span> mempunyai kandungan gizi sangat baik, antara lain menyediakan energi cukup tinggi dibandingkan dengan buah-buahan lain. Pisang kaya mineral seperti kalium, magnesium, fosfor, besi, dan kalsium. Pisang juga mengandung vitamin, yaitu C, B kompleks, B6, dan serotonin yang aktif sebagai neurotransmitter dalam kelancaran fungsi otak.</p></div>"  
},
{
    "nama" : "Melon",
    "namalatin" : "Cucumis melo",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Buah</span> melon (curcumis melo) masih bersaudaran dengan labu, blewah dan buah semangka. Melon termasuk dalam keluarga Cucurbitaceae. Daging buah melon memiliki tekstur yang lebut dengan rasa yang manis dan menyegarkan karena mengandung banyak air.Buah melon biasanya digunakan sebagai buah meja. Aatau bisa juga dijadikan jus, dan campuran minuman segar dingin. Namun manfaat buah melon bukan hanya sebagai makanan, akan tetapi juga berkhasiat untuk kesehatan. Hal ini karena kandungan nutrisi yang terdapat pada buah ini cukup banyak.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Kandungan</span> gizi buah melon memang cukup lengkap. Maka tidak heran jika buah segar ini juga memiliki segudang manfaat bagi kesehatan. Berikut ini beberapa khasiat buah melon untuk kesehatan, kecantikan dan membantu program diet.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Selain</span> memiliki rasa yang segar, buah melon juga mengandung segudang nutrisi penting yang dibutuhkan tubuh. Dalam 100 gram daging buah melon terdapat zat gizi penting seperti, karbohidrat 14,8 gr, protein 1,55 gr, lemak 0,5 gr, potassium 546,9 mg, vitamin A 5.706,5 IU (mencukupi 64 persen kebutuhan vitmain A harian), dan vitamin C 74,7 mg (mencukupi 12 persen kebutuhan vitamin C harian).</p></div>"  
},
{
    "nama" : "Durian",
    "namalatin" : "Durio zibethinus",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Durian</span> adalah nama tumbuhan tropis yang berasal dari wilayah Asia Tenggara, sekaligus nama buahnya yang bisa dimakan. Nama ini diambil dari ciri khas kulit buahnya yang keras dan berlekuk-lekuk tajam sehingga menyerupai duri. Sebutan populernya adalah "raja dari segala buah" (King of Fruit). Durian adalah buah yang kontroversial, meskipun banyak orang yang menyukainya, namun sebagian yang lain malah muak dengan aromanya</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Durian</span> terutama dipelihara orang untuk buahnya, yang umumnya dimakan (arilus atau salut bijinya) dalam keadaan segar. Salut biji ini umumnya manis dan sangat bergizi karena mengandung banyak karbohidrat, lemak, protein, dan mineral.[4]Pada musim raya durian, buah ini dapat dihasilkan dengan berlimpah, terutama di sentra-sentra produksinya di daerah. Secara tradisional, daging buah yang berlebih-lebihan ini biasa diawetkan dengan memasaknya bersama gula menjadi dodol durian (biasa disebut lempok), atau memfermentasikannya menjadi tempoyak. Selanjutnya, tempoyak yang rasanya masam ini biasa menjadi bahan masakan seperti sambal tempoyak, atau untuk campuran memasak ikan.Durian pun kerap diolah menjadi campuran bahan kue-kue tradisional, seperti gelamai atau jenang. Terkadang, durian dicampurkan dalam hidangan nasi pulut (ketan) bersama dengan santan. Dalam dunia masa kini, durian (atau aromanya) biasa dicampurkan dalam permen, es krim, susu, dan berbagai jenis minuman penyegar lainnya.Bijinya bisa dimakan sebagai camilan setelah direbus atau dibakar,[4] atau dicampurkan dalam kolak durian. Biji durian yang mentah beracun dan tak dapat dimakan karena mengandung asam lemak siklopropena (cyclopropene).[10] </p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Biji</span> durian mengandung sekitar 27% amilosa.[11] Kuncup daun (pucuk), mahkota bunga, dan buah yang muda dapat dimasak sebagai sayuran.</p></div>"  
},
{
    "nama" : "Belimbing",
    "namalatin" : "Averrhoa carambola",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Buah</span> belimbing berwarna kuning kehijauan. Saat baru tumbuh, buahnya berwarna hijau. Jika dipotong, buah ini mempunyai penampang yang berbentuk bintang. Berbiji kecil dan berwarna coklat. Buah ini renyah saat dimakan, rasanya manis dan sedikit asam. Buah ini mengandung banyak vitamin C.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Dengan</span> cara dimakan biasa atau dijadikan juice, Belimbing Manis memiliki banyak manfaat sebagai obat tradisional atau obat alternatif. Kandungan vitamin C yang tinggi dalam buah Belimbing Manis bermanfaat sebagai antioksidan yang berfungsi untuk memerangi radikal bebas dan mencegah penyebaran sel-sel kanker, meningkatkan daya tahan tubuh, dan mencegah sariawan. Pektin yang terdapat dalam buah Belimbing Manis mampu mengikat kolesterol dan asam empedu dalam usus, kemudian membantu pengeluarannya sehingga dapat menurunkan kadar kolesterol dalam darah dan melancarkan pencernaan. Sedangkan kandungan Kalium yang tinggi dan Natrium yang rendah sangat memungkinkan Belimbing Manis dijadikan sebagai obat anti hipertensi.</p></div>" , 
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>Belimbing manis merupakan buah yang kaya vitamin A dan C yang bersifat antioksidan dan kalium. Yang patut diperhitungkan juga adalah seratnya, terutama serat pektin yang berguna bagi kesehatan pembuluh darah.</p></div>"  
},
{
    "nama" : "Stroberi",
    "namalatin" : "Fragaria vesca",
    "deskripsi" : '<div class="tulisan"><p><span style="margin-left:30px">Strawberry</span> merupakan buah yang sangat baik untuk kesehatan tubuh, dengan warna yang merah menggoda dan bentuknya yang sangat menarik membuat kita tertarik untuk mengkonsumsinya, meskipun rasanya sedikit asam namun sangat banyak digemari karena khasiatnya yang juga luar biasa.</p></div>',
    "hasilguna" :"<div class='tulisan'><p><span style='margin-left:30px'>Anti</span> kanker, kandungan anti oksidan yang tinggi dalam strawberry sangat baik untuk kesehatan tubuh kita supaya kita dapat terhindar dari berbagai penyakit berbahaya seperti kanker, karena anti oksidannya sangat berperan dalam mencegah kerusakan sel dan mengatasi radikal bebas di dalam tubuh.</p></div>",
    "kandungan" : "<div class='tulisan'><p><span style='margin-left:30px'>energi</span> 50 kalori protein 1 gram karbohidrat 11,65 gram serat 3,81 gram kalsium 23, 24 mg magnesium 16,60 mg fosfor 31,54 mg potasium 44,82 mg selenium 1,16 mg vitamin C 94,12 mg Folat 29,38 mg Vitamin A 44,82 IU</p></div>"  
}];